language: go

go:
 - 1.4

script:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v ./...
  - go vet ./...
  - docs/project-code-coverage.sh

notifications:
  email:
    - marty.schoch@gmail.com
